ALTER TABLE notes ADD COLUMN IF NOT EXISTS encrypted BOOLEAN DEFAULT FALSE;
ALTER TABLE notes ADD COLUMN IF NOT EXISTS encryption_iv TEXT;
ALTER TABLE notes ADD COLUMN IF NOT EXISTS encryption_salt TEXT;

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS encrypted BOOLEAN DEFAULT FALSE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS encryption_iv TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS encryption_salt TEXT;
